# Generated by Django 4.2.2 on 2023-08-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='InactiveDate',
            field=models.DateField(null=True),
        ),
    ]
