# Generated by Django 4.2.2 on 2023-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchID', models.IntegerField(unique=True)),
                ('BranchName', models.CharField(max_length=15)),
                ('ActiveFlag', models.IntegerField(default=1)),
                ('InactiveDate', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrokerID', models.IntegerField(unique=True)),
                ('BrokerName', models.CharField(max_length=15)),
                ('ActiveFlag', models.IntegerField(default=1)),
                ('InactiveDate', models.DateField(null=True)),
            ],
        ),
    ]
